# Generated by Django 5.1.1 on 2024-09-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='state',
            new_name='done',
        ),
    ]
